version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9002:9000"
    volumes:
      - ./volumes/sonarqube_data:/opt/sonarqube/data
      - ./volumes/sonarqube_logs:/opt/sonarqube/logs
      - ./volumes/sonarqube_temp:/opt/sonarqube/temp
    networks:
      - devops_network

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - ./volumes/sonatype_work:/sonatype-work
      - ./volumes/nexus_data:/nexus-data
    networks:
      - devops_network

networks:
  devops_network:
    external: true

volumes:
  jenkins_home:
  nexus_data:
  mysql_data: